Repository prommis/prommis, pull requests merged in 2024-03, with the labels that each got.

#34 UKy Flowsheet Jupyter Notebook
  docs/_toc.yml
  docs/tutorials/uky_flowsheet-solution.ipynb
  docs/tutorials/uky_flowsheet.png
  src/prommis/uky/tests/test_uky_flowsheet.py
  src/prommis/uky/uky_flowsheet.py
Labels: Priority:Normal

#36 Add Costing to UKy Flowsheet
  src/prommis/roasting/feed_roaster_flowsheet.py
  src/prommis/roasting/ree_feed_roaster.py
  src/prommis/roasting/ree_oxalate_roaster.py
  src/prommis/uky/tests/test_uky_flowsheet.py
  src/prommis/uky/uky_flowsheet.py
Labels: Priority:Normal

#43 Update to IDAES 2.4.0 and WaterTAP 0.12.0
  pyproject.toml
  requirements-dev.txt
Labels: Priority:High, WaterTAP, IDAES

#51 Ensure WaterTAP is imported if available and add workaround for SX model test failures
  src/prommis/conftest.py
  src/prommis/solvent_extraction/tests/test_sx_model.py
Labels: Priority:High, WaterTAP

#49 Nanofiltration example flowsheet
  src/prommis/nanofiltration/README.md
  src/prommis/nanofiltration/__init__.py
  src/prommis/nanofiltration/nf_brine.py
  src/prommis/nanofiltration/nf_brine_plot.py
  src/prommis/nanofiltration/tests/__init__.py
  src/prommis/nanofiltration/tests/test_nf_brine.py
Labels: Priority:Normal
