Repository prommis/prommis, pull requests merged in 2024-09, with the labels that each got.

#90 More REE Costing Improvements
  src/prommis/uky/costing/custom_costing_example.py
  src/prommis/uky/costing/ree_plant_capcost.py
  src/prommis/uky/costing/tests/test_ree_costing.py
  src/prommis/uky/uky_flowsheet.py
Labels: Priority:Normal

#88 Adds Liquid Inlet to Roaster & Adds Var for Mass Flow
  docs/tutorials/uky_flowsheet-solution.ipynb
  src/prommis/roasting/oxalate_roaster_flowsheet.py
  src/prommis/roasting/ree_feed_roaster.py
  src/prommis/roasting/ree_oxalate_roaster.py
  src/prommis/roasting/tests/test_ree_feed_roaster.py
  src/prommis/roasting/tests/test_ree_oxalate_roaster.py
  src/prommis/uky/tests/test_uky_flowsheet.py
  src/prommis/uky/uky_flowsheet.py
Labels: Priority:Normal, enhancement

#95 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: Priority:High
