Repository prommis/prommis, pull requests merged in 2024-05, with the labels that each got.

#69 Add Solvent Extraction documentation
  docs/api.rst
  src/prommis/solvent_extraction/ree_aq_distribution.py
  src/prommis/solvent_extraction/ree_og_distribution.py
  src/prommis/solvent_extraction/solvent_extraction.py
  src/prommis/solvent_extraction/sx_model_flowsheet_steady_state.py
  src/prommis/solvent_extraction/sx_stripping_flowsheet_steady.py
Labels: Priority:High, documentation

#26 Interface to UI for UKy
  src/prommis/_sphinx_extensions/chem.py
  src/prommis/examples/__init__.py
  src/prommis/examples/uky_fv.py
  src/prommis/examples/util.py
  src/prommis/uky/tests/test_uky_flowsheet_ui.py
  src/prommis/uky/uky_flowsheet_ui.png
  src/prommis/uky/uky_flowsheet_ui.py
Labels: Priority:Normal, WaterTAP

#68 Adding review/merge requirements to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Priority:Normal

#70 Roaster unit models with updated docstring
  src/prommis/precipitate/precipitate_liquid_properties.py
  src/prommis/precipitate/precipitate_solids_properties.py
  src/prommis/precipitate/tests/test_precipitator.py
  src/prommis/roasting/ree_feed_roaster.py
  src/prommis/roasting/ree_oxalate_roaster.py
  src/prommis/uky/tests/test_uky_flowsheet.py
Labels: Priority:Normal
