Repository prommis/prommis, pull requests merged in 2024-01, with the labels that each got.

#21 Add Spell Checker
  .github/workflows/core.yml
  docs/tutorials/diafiltration-solution.ipynb
  docs/tutorials/diafiltration.ipynb
  pyproject.toml
  src/prommis/roasting/feed_roaster_flowsheet.py
  src/prommis/roasting/oxalate_roaster_flowsheet.py
  src/prommis/roasting/ree_feed_roaster.py
Labels: Priority:Normal

#27 Add WaterTAP dependency
  pyproject.toml
  requirements-dev.txt
Labels: Priority:High, WaterTAP

#22 Integration of waterTAP costing package.
  src/prommis/leaching/tests/test_leach_flowsheet.py
  src/prommis/uky/costing/ree_plant_capcost.py
  src/prommis/uky/costing/tests/test_ree_costing.py
Labels: Priority:Normal, WaterTAP

#28 Update README to add note for developers to run spell checker before pushing code
  README.md
Labels: Priority:Normal
