Repository prommis/prommis, pull requests merged in 2024-04, with the labels that each got.

#44 Touch Properties in UKy Flowsheet
  src/prommis/uky/uky_flowsheet.py
Labels: Priority:Normal

#56 Configure docs to include autogenerated API reference
  docs/.gitignore
  docs/_config.yml
  docs/_toc.yml
  docs/api.rst
  src/prommis/_sphinx_extensions/chem.py
  src/prommis/roasting/ree_feed_roaster.py
  src/prommis/solvent_extraction/solvent_extraction.py
  src/prommis/solvent_extraction/sx_model_flowsheet_steady_state.py
  src/prommis/solvent_extraction/sx_stripping_flowsheet_steady.py
Labels: Priority:High, documentation

#71 Fix misnamed property in leaching package
  src/prommis/leaching/leach_solution_properties.py
  src/prommis/leaching/tests/test_leach_solution.py
  src/prommis/solvent_extraction/ree_aq_distribution.py
  src/prommis/solvent_extraction/ree_og_distribution.py
Labels: Priority:Normal, bug

#61 UKy Flowsheet Documentation
  docs/api.rst
  docs/tutorials/uky_flowsheet.png
  src/prommis/uky/uky_flowsheet.py
Labels: Priority:High
