Repository prommis/prommis, pull requests merged in 2025-03, with the labels that each got.

#123 Added_byproduct_recovery_determine_method
  pyproject.toml
  src/prommis/uky/costing/byproduct_recovery_determination_tree.png
  src/prommis/uky/costing/costing_dictionaries.py
  src/prommis/uky/costing/determine_byproduct_recovery.py
  src/prommis/uky/costing/ree_plant_capcost.py
  src/prommis/uky/costing/tests/test_determine_byproduct_recovery.py
  src/prommis/uky/costing/tests/test_ree_costing.py
  src/prommis/uky/tests/test_uky_flowsheet.py
Labels: Priority:Normal, costing

#129 Correct Leaching Component Recovery Calculation
  src/prommis/uky/uky_flowsheet.py
Labels: Priority:Normal

#125 Adding Leaching Robustness Tests
  src/prommis/leaching/leach_train.py
  src/prommis/leaching/tests/test_leach_train.py
Labels: Priority:Normal

#128 Adding Roasting Robustness Tests
  src/prommis/roasting/tests/test_ree_oxalate_roaster.py
Labels: Priority:Normal

#104 Added multi-stage membrane cascade flowsheet
  src/prommis/nanofiltration/membrane_cascade_flowsheet/README.md
  src/prommis/nanofiltration/membrane_cascade_flowsheet/__init__.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/diafiltration_flowsheet_model.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/flowsheet.png
  src/prommis/nanofiltration/membrane_cascade_flowsheet/membrane.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/precipitator.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/solute_property.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/solve_diafiltration.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/tests/__init__.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/tests/test_flowsheet.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/tests/test_membrane.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/tests/test_precipitator.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/tests/test_solute_property.py
  src/prommis/nanofiltration/membrane_cascade_flowsheet/utils.py
Labels: Priority:High

#133 make the recovery rate an expression
  src/prommis/uky/costing/ree_plant_capcost.py
  src/prommis/uky/costing/tests/test_ree_costing.py
Labels: Priority:High

#121 Adding a sample About paragraph to docs
  docs/index.md
Labels: Priority:Normal, documentation

#126 Update watertap requirement after IDAES 2.8.0
  pyproject.toml
  src/prommis/uky/uky_flowsheet_ui.py
Labels: Priority:High, WaterTAP, IDAES
